### ISSUE TITLE
database update problem

### ISSUE THREAD

**Issue by MustafaDogan78** [backdrop-contrib/riddler#6] opened 2021-03-25 21:21 UTC
After the last update, the database update results in a white page. There is an error.

**Comment by indigoxela** [comment] 2021-03-26 06:18
Oops! Is there still a white page after update, or did it just happen when the update was running?

**Comment by indigoxela** [comment] 2021-03-26 06:30
I tried to reproduce it, but wasn't able to.

I installed 1.x-1.0.0 (the previous version), configured a riddle, then updated via user interface to 1.x-1.0.1. It worked smoothly.
Are you sure, that the riddler module was causing the error?

**Comment by MustafaDogan78** [comment] 2021-03-26 10:54
First of all, I have to say this. I upgraded my website from Drupal7. I will write down the problem in items.
1. Install the previous version of the riddler module.
2. Go to the update page from the admin panel.
3. Mark the riddler and run the update.
4. Run update.php.
5. Click the pending update link.
6. There are riddler waiting.
7. Continue to update.
8. Unfortunately, the blank white page.

**Comment by indigoxela** [comment] 2021-03-26 13:46
> First of all, I have to say this. I upgraded my website from Drupal7.

Many thanks for this info, it might be relevant here.

Now to the white page: do you have access to the webserver logfiles? Does the Backdrop dblog provide any details?
You find the latter on /admin/reports/dblog.

The only difference I currently see, is that my site was not upgraded from Drupal. Just to make sure: did the previous version 1.x-1.0.0 run without problems on your site?

What are the contents of your riddler settings? You can export them via /admin/config/development/configuration/single/export.

As "Configuration group" choose "Configuration" as "Configuration name" choose "Captcha Riddler Settings".
You can also view that configuration on the file system, it's the file "riddler.settings.json" in your active configuration directory - in case you have access to it.

**Comment by indigoxela** [comment] 2021-03-26 16:50
@MustafaDogan78 In case, you're curious, why I ask for the config file contents, when you have a problem with a "database update", here's the explanation:

The only thing this update does, is to add some additional lines to the config file (riddler.settings.json). The riddler module has no database at all. So whatever goes so terribly wrong, must have to do something with this file.

**Comment by MustafaDogan78** [comment] 2021-03-26 17:33
module is working. doing his duty. The problem is after update.php. The site or module is not broken. there is no problem since it works. Could be from Drupal7 upgrade. I'm sorry I couldn't think of this before. We can close this place. I'm already planning to return to drupal7 by November 2022. 1.18.2 update has been done without considering the screen reader. 2426 Turkish translations I have made are still pending approval. Things are very slow here. Nobody has time except a few friends.
You and a few friends answered me very quickly, very quickly. Thank you very much for that. Goodbye.

**Comment by indigoxela** [comment] 2021-03-27 12:12
@MustafaDogan78 No, please let's not close this issue yet. I'm really trying to understand what's happening and how to solve this.

So, again, is there something special about the file "riddler.settings.json"? What are the contents? You can either export it via user interface or access the file directly, it's placed in your Backdrop active config directory.

**Comment by MustafaDogan78** [comment] 2021-03-27 12:53
{
    "_config_name": "riddler.settings",
    "_config_translatables": [
        "riddler_questions.330e095b-321a-4a91-9dc3-94f203858770.question",
        "riddler_questions.330e095b-321a-4a91-9dc3-94f203858770.answer",
        "riddler_questions.8706d719-bf6a-40d6-a9fa-6fced0e5a924.question",
        "riddler_questions.8706d719-bf6a-40d6-a9fa-6fced0e5a924.answer",
        "riddler_questions.40092ac0-7223-49c7-bab8-52489a5ec7b5.question",
        "riddler_questions.40092ac0-7223-49c7-bab8-52489a5ec7b5.answer",
        "riddler_questions.1a90cf43-302e-4459-afb8-961c8627b0fa.question",
        "riddler_questions.1a90cf43-302e-4459-afb8-961c8627b0fa.answer",
        "riddler_questions.10feff19-fa3c-4b3f-aca1-f97d50472bce.question",
        "riddler_questions.10feff19-fa3c-4b3f-aca1-f97d50472bce.answer",
        "riddler_questions.2cd8e15f-7445-46b2-9434-1882e59adb94.question",
        "riddler_questions.2cd8e15f-7445-46b2-9434-1882e59adb94.answer",
        "riddler_questions.c06e8fd8-9ad5-4438-b5c1-dca02e5f3d16.question",
        "riddler_questions.c06e8fd8-9ad5-4438-b5c1-dca02e5f3d16.answer",
        "riddler_questions.16ee1156-a2a2-45d3-a07b-3059ced38ff5.question",
        "riddler_questions.16ee1156-a2a2-45d3-a07b-3059ced38ff5.answer",
        "riddler_questions.94a52980-dbe3-4ab3-b436-9373a08cec64.question",
        "riddler_questions.94a52980-dbe3-4ab3-b436-9373a08cec64.answer",
        "riddler_questions.f88d8921-ab48-471e-853e-626fce81304a.question",
        "riddler_questions.f88d8921-ab48-471e-853e-626fce81304a.answer",
        "description"
    ],
    "riddler_weight": "-10",
    "riddler_questions": {
        "330e095b-321a-4a91-9dc3-94f203858770": {
            "question": "Hangisi canlı varlık? Aşağıya yazınız.Sandalye Gemi demir Karga tren",
            "answer": "karga"
        },
        "8706d719-bf6a-40d6-a9fa-6fced0e5a924": {
            "question": "Hangisi canlı varlık değil? Aşağıya yazınız.Tavuk İnek Köpek Kedi At Koltuk",
            "answer": "koltuk"
        },
        "40092ac0-7223-49c7-bab8-52489a5ec7b5": {
            "question": "Şu şehirlerden hangisi Türkiye'de değil?İstanbul Ankara yozgat Bursa Bolu atina Konya",
            "answer": "atina"
        },
        "1a90cf43-302e-4459-afb8-961c8627b0fa": {
            "question": "İkiden sonra hangi sayı gelir? (rakamla yazınız.)",
            "answer": "3"
        },
        "10feff19-fa3c-4b3f-aca1-f97d50472bce": {
            "question": "istanbul kelimesindeki son harf nedir?",
            "answer": "l"
        },
        "2cd8e15f-7445-46b2-9434-1882e59adb94": {
            "question": "ankara kelimesinin sondan ikinci harfi nedir?",
            "answer": "r"
        },
        "c06e8fd8-9ad5-4438-b5c1-dca02e5f3d16": {
            "question": "konya Mardin denizli İzmir manisa sıralamasında, üçüncü sıraya hangi il yazılmıştır?",
            "answer": "denizli"
        },
        "16ee1156-a2a2-45d3-a07b-3059ced38ff5": {
            "question": "yılın ilk ayı nedir?",
            "answer": "ocak"
        },
        "94a52980-dbe3-4ab3-b436-9373a08cec64": {
            "question": "haftanın son günü nedir?",
            "answer": "pazar"
        },
        "f88d8921-ab48-471e-853e-626fce81304a": {
            "question": "1 yıl kaç gündür? (Rakamla yazınız.)",
            "answer": "365"
        }
    },
    "use_description": 1,
    "description": "Dikkat! Bu alanın doldurulması zorunludur."
}

**Comment by indigoxela** [comment] 2021-03-27 13:11
@MustafaDogan78 many thanks for the info.

Your json content proves that the update *did* run. The new config items got added, so the error must be caused by something else.
I verified that the json file content is OK, by running the same update with this file in place - no problems.

It would be essential to get the apache (or nginx, or php) error log messages when you get the white page. Otherwise we will not be able to find the reason.

And again: is there anything unusual in your dblog on /admin/reports/dblog?

**Comment by MustafaDogan78** [comment] 2021-03-27 16:25
site could be drupal7 upgrade. I uninstalled the plugin and reinstalled it seems no problem. Thanks. Same problem arose, let module uninstall and install.

**Comment by indigoxela** [comment] 2021-03-28 15:26
@MustafaDogan78 I'm glad that you found a solution for your site.

I really would have appreciated the related webserver log entries, but as you don't seem to have access to them, I'll close this issue for now. Feel free to re-open, if there are more findings regarding a possible root cause. (I still can't reproduce the problem.)

**Closed as completed** 2021-03-28 15:26 UTC
